---
# tasks file for apache2
- name: Make sure pymysql is present
  become: true # needed if the other tasks are not played as root
  pip:
    name: pymysql
    state: present
- name: install web components
  apt: 
    state: present 
    name: ['apache2', 'libapache2-mod-wsgi']

- name: ensure mod_wsgi enabled
  apache2_module: state=present name=wsgi
  notify: restart apache2

- name: de-activate default apache site
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache2

- name: ensure apache started
  service: name=apache2 state=started enabled=yes
