---
# tasks file for loadbalancer

- name: install tools
  apt:
    name:
      - python-httplib2
    state: present

- name: install nginx
  apt: name=nginx state=present update_cache=ye

- name: configure nginx site
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/demo mode=0644
  notify: restart nginx

- name: de activate nginx default
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx

- name: activate demo site
  file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
  notify: restart nginx

- name: ensure ngnix started
  service: name=nginx state=started enabled=yes