---
# tasks file for database
- name: install tools
  apt:
    name: ['python-mysqldb']
    state: present
    update_cache: yes
- name: install mysql
  apt: name=mysql-server state=present update_cache=yes
- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf line="bind-address = {{ ansible_eth0.ipv4.address }} "
  notify: restart mysql
- name: ensure mysql started
  service: name=mysql state=started enabled=yes
- name: create db
  mysql_db: name=demo state=present
- name: create user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%'