---
  - hosts: database
    become: yes
    tasks:
      - name: install tools
        apt:
          name: ['python-mysqldb']
          state: present
          update_cache: yes
      - name: install mysql
        apt: name=mysql-server state=present update_cache=yes
      - name: ensure mysql listening on all ports
        lineinfile: dest=/etc/mysql/my.cnf line="bind-address = 0.0.0.0"
        notify: restart mysql
      - name: ensure mysql started
        service: name=mysql state=started enabled=yes

      - name: create db
        mysql_db: name=demo state=present
      
      - name: create user
        mysql_user: name=demo password=demo priv=demo.*:ALL host='%'
    handlers:
      - name: restart mysql
        service: name=mysql state=restarted