---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: stop loadbalancer
        service: name=nginx state=stopped
      - wait_for: port=80 state=drained
      
  - hosts: webserver
    become: true
    tasks:
      - name: stop webserver
        service: name=apache2 state=stopped
      - wait_for: port=80 state=stopped

  - hosts: database
    become: true
    tasks:
      - name: restart database
        service: name=mysql state=restarted
      - wait_for: port=3306 state=started
  - hosts: loadbalancer
    become: true
    tasks:
      - name: start loadbalancer
        service: name=nginx state=started
      - wait_for: port=80
  - hosts: webserver
    become: true
    tasks:
      - name: start webserver
        service: name=apache2 state=started
      - wait_for: port=80