---
  - hosts: apps
    become: yes
    tasks:
      - name: install web components
        apt: 
          state: present 
          update_cache: yes
          name: ['apache2', 'libapache2-mod-wsgi', 'python-pip', 'python-virtualenv']
      - name: ensure apache started
        service: name=apache2 state=started enabled=yes